name: Cowsay CI

on:
  push:
    branches:
      - main

jobs:
  build_and_package_application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t cowsay-app:latest .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 cowsay-app:latest
